config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show], :controllers => { :registrations => "users/registrations" }
  resources :products do
    resources :reviews
  end

  root to: 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :user

  has_attached_file :imgfile, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imgfile, content_type: /\Aimage\/.*\z/

  validates :name, :presence => true
  validates :details, :presence => true
  validates :cost, :presence => true
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def index

    @user = current_user
    @products = @user.products
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(:name => product_params[:name], :details => product_params[:details], :cost => product_params[:cost], :imgfile => product_params[:imgfile], :user_id => current_user.id)
    if @product.save
      flash[:notice] = "Product added!"
      redirect_to products_path
    else
      flash[:notice] = "Product not added!"
      render :new
    end
  end

  def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product updated!"
        redirect_to products_path
      else
        render :edit
      end
    end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted!"
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:title, :details, :imgfile)
  end
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    # @user = current_user
    # @products = @user.products
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(:name => product_params[:name], :details => product_params[:details], :cost => product_params[:cost], :imgfile => product_params[:imgfile], :user_id => current_user.id)
    if @product.save
      flash[:notice] = "Product added!"
      redirect_to products_path
    else
      flash[:notice] = "Product not added!"
      render :new
    end
  end

  def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:notice] = "Product updated!"
        redirect_to products_path
      else
        render :edit
      end
    end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted!"
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :details, :cost, :imgfile)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_form.html.erb
<div class="well bgWhite">
  
  <%= form_for @product do |f| %>
    <%= f.label :name,'Product Name' %>
    <%= f.text_field :name, :class => 'form-control' %>
    <%= f.label :details,'Product Details' %>
    <%= f.text_field :details, :class => 'form-control' %>
    <%= f.label :cost,'Product Cost' %>
    <%= f.text_field :cost, :class => 'form-control' %>
    <%= f.label :imgfile, 'Image File' %>
    <%= f.file_field :imgfile %>
    <%= f.submit %>
  <% end %>

</div>

app/views/products/edit.html.erb
<div class="siteTitle">
  <a href="/products">Craftsy</a>
</div>
<div class="well">
  <h1 class="centerHeader">Edit Product</h1>
  <%= render "form" %>
</div>

app/views/products/index.html.erb
<div class="siteTitle">
  <a href="/products">Craftsy</a>
</div>
<div class="well centerHeader">
  <% if current_user %>
    <% if current_user.admin?%>
  <%= link_to "Create New Product", new_product_path, :class => "bigLink"%>
  <br><br>
  <% end %>
  <% end %>
  <% if @products.any? %>
  <div class="row" id="topMargin">
    <% @products.each do |product| %>
    <div class="col m4">
      <div class="card">
        <div class="card-image">
            <a href="/products/<%= product.id %>"><%= image_tag product.imgfile, :class => "thisImage"  %></a>
        </div>
        <div class="card-content">
          <span class="card-title"> <%= product.name %> </span>
          <p><%= product.details %></p>
          <br><span>

          <div class="chip">

            <%= product.cost %>
          </div>
          <a href="/products/<%= product.id %>" class="btn-floating waves-effect waves-light red"><i class="material-icons">info_outline</i></a>
        </span>
        </div>
      </div>
    </div>
    <% end %>
  <% else %>
  <div class="centerText">
    <h1>There are no products to display</h1>
    <a href="/users/sign_in"><h3>Click here to Log In</h3></a>
    <a href="/users/sign_up"><h3>Click here to Sign Up</h3></a>
  </div>

  <% end %>
  </div>




</div>

app/views/products/new.html.erb
<div class="siteTitle">
  <a href="/products">Craftsy</a>
</div>
<div class="well">
  <h1 class="centerHeader">Create New Product</h1>
  <%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="siteTitle">
  <a href="/products">Craftsy</a>
</div>

<div class="well">
  <div class="card">
    <div class="card-image resizeImg">
      <%= image_tag @product.imgfile%>
    </div>
    <div class="card-content">
      <span class="card-title centerText"> <%= @product.name %> <%= @product.cost %> | <%= @product.details %>
        <% if current_user %>
          <% if current_user.admin?%> | <%= link_to "Edit Product", edit_product_path %>  |  <%= link_to "Delete Product", product_path, :data => {:confirm => "Are you sure?",:method => "delete"} %></span>
          <% end %>
        <% end %>
        <div class="well">
          <h2 style="text-align: center; color: white;">Product Reviews</h2>
          <h5 style="text-align: center;"><%= link_to "Add a review", new_product_review_path(@product) %></h5>
          <br><br> <h3 style="text-align: center; color: white;"><%= flash[:alert] %><%= flash[:notice] %></h3>
          <br><br>
          <% if @reviews.any? %>
            <% @reviews.each do |review| %>
              <h5><%= review.title %> </h5>
              <% if current_user %>
                <% if current_user.admin?%>
                <%= link_to "Delete Review", product_review_path(@product, review), :data => {:confirm => "Are you sure?",:method => "delete"} %>
                <% end %>
              <% end %>
              <br>
              by <i><%= review.name %></i> (<%= review.created_at %>)
              <br>
              <%= review.content %>
              <br><br>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>